### ISSUE TITLE
Fix slow tests (ListDocumentsAuthorizeCypher in authorisation.go)

### ISSUE THREAD

**Issue by indyboox** [indykite/neo4j-graph-tool-core#216]
We ran into slow tests because of the ListDocumentsAuthorizeCypher in [authorisation.go](https://github.com/indykite/jarvis-proto/blob/master/pkg/cypher/authorisation.go). The troubled test data is edited in such a way that the tests will hit the least on tests and make them passed.

**Comment by bayegan** [comment]
Duplicate of https://github.com/orgs/indykite/projects/44
